version: '2'
services:
  exonimble-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/exoNimble/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=exoNimble
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
